import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <video className="bg-video" src={require('../../public/bg-video.mp4')} type='video/mp4' autoPlay={true} loop={true} playsInline muted width="100%"/>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
